-- CreateEnum
CREATE TYPE "NOTIFICATION_TYPE" AS ENUM ('POST_STATUS_PROCESSING', 'POST_STATUS_SUCCESS', 'POST_STATUS_FAILED', 'SYSTEM_ALERT');

-- CreateEnum
CREATE TYPE "STATUS" AS ENUM ('SUCCESS', 'FAILED', 'PENDING', 'REFUNDED', 'CANCELLED', 'PAUSED');

-- CreateTable
CREATE TABLE "Notification" (
    "id" SERIAL NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "NOTIFICATION_TYPE" NOT NULL,
    "message" TEXT NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
